// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vibhcunfdtdosqzalnqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpYmhjdW5mZHRkb3NxemFsbnF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5ODcxNzMsImV4cCI6MjA2NzU2MzE3M30.RNwspPu_-SiH3wKZA-lUC3vpUPopeJ_jqqQ47nQOtiw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});